name: "ray-assistant"
cluster_env: ray-assistant
ray_serve_config:
  import_path: app.serve:deployment
  runtime_env:
    working_dir: "https://github.com/ray-project/llm-applications/archive/refs/tags/v0.0.1.zip"
